
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: shop_development
  
test:
  <<: *default
  database: shop_test

production:
  <<: *default
  database: shop_production
  password: <%= ENV['MYAPP_DATABASE_PASSWORD']
